"""domain foundation"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acl_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("scope_pattern", sa.Text(), nullable=False),
        sa.Column("expected_owner_identity", sa.String(length=255), nullable=True),
        sa.Column("inheritance_expected", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "health_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("domain", sa.String(length=32), nullable=False),
        sa.Column("policy_type", sa.String(length=64), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING','RETRY','COMPLETE','FAILED')", name="ck_job_status"
        ),
        sa.CheckConstraint("attempts >= 0 AND max_attempts > 0", name="ck_job_attempts"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index("ix_jobs_status_due", "jobs", ["status", "next_attempt_at"], unique=False)
    op.create_table(
        "principals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("identity_namespace", sa.String(length=255), nullable=False),
        sa.Column("sid", sa.String(length=255), nullable=False),
        sa.Column("account_name", sa.String(length=255), nullable=True),
        sa.Column("principal_type", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_namespace", "sid", name="uq_principal_identity"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "source_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("fqdn", sa.String(length=255), nullable=True),
        sa.Column("instance_id", sa.String(length=255), nullable=False),
        sa.Column("expected_cadence_seconds", sa.Integer(), server_default="60", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("source_type IN ('FILESERVER','PVE','PBS')", name="ck_source_type"),
        sa.CheckConstraint("expected_cadence_seconds > 0", name="ck_source_cadence"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_type", "instance_id", name="uq_source_identity"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("auth_provider", sa.String(length=32), nullable=False),
        sa.Column("provider_subject", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth_provider", "provider_subject", name="uq_user_provider_subject"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "ad_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["principal_id"], ["principals.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("principal_id", name="uq_ad_group_principal"),
    )
    op.create_table(
        "backup_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("job_identity", sa.String(length=255), nullable=False),
        sa.Column("workload_identity", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_node_id", "job_identity", name="uq_backup_job_identity"),
    )
    op.create_table(
        "collectors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("collector_type", sa.String(length=32), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "diagnostic_bundles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("trigger_type", sa.String(length=64), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("storage_reference", sa.Text(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.CheckConstraint("last_event_at >= first_event_at", name="ck_diagnostic_range"),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "discovery_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("scope_identity", sa.Text(), nullable=False),
        sa.Column("extensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_files", sa.Integer(), nullable=False),
        sa.Column("max_bytes", sa.BigInteger(), nullable=False),
        sa.Column("parser", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("max_files > 0 AND max_bytes > 0", name="ck_discovery_limits"),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "health_signals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("domain", sa.String(length=32), nullable=False),
        sa.Column("signal_type", sa.String(length=64), nullable=False),
        sa.Column("scope_identity", sa.String(length=255), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("measurement", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_signals_source_domain_time",
        "health_signals",
        ["source_node_id", "domain", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "hygiene_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("scope_identity", sa.Text(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quality", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("domain", sa.String(length=32), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_node_id", "fingerprint", name="uq_incident_fingerprint"),
    )
    op.create_table(
        "metric_samples_1d",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("metric_name", sa.String(length=128), nullable=False),
        sa.Column("scope_identity", sa.String(length=255), server_default="source", nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("quality", sa.String(length=16), server_default="COMPLETE", nullable=False),
        sa.Column("sample_count", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("sample_count > 0", name="ck_metric_samples_1d_sample_count"),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_metric_samples_1d_source_metric_time",
        "metric_samples_1d",
        ["source_node_id", "metric_name", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "metric_samples_1h",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("metric_name", sa.String(length=128), nullable=False),
        sa.Column("scope_identity", sa.String(length=255), server_default="source", nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("quality", sa.String(length=16), server_default="COMPLETE", nullable=False),
        sa.Column("sample_count", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("sample_count > 0", name="ck_metric_samples_1h_sample_count"),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_metric_samples_1h_source_metric_time",
        "metric_samples_1h",
        ["source_node_id", "metric_name", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "metric_samples_1m",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("metric_name", sa.String(length=128), nullable=False),
        sa.Column("scope_identity", sa.String(length=255), server_default="source", nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("quality", sa.String(length=16), server_default="COMPLETE", nullable=False),
        sa.Column("sample_count", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("sample_count > 0", name="ck_metric_samples_1m_sample_count"),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_metric_samples_1m_source_metric_time",
        "metric_samples_1m",
        ["source_node_id", "metric_name", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "policy_exceptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("scope_identity", sa.String(length=255), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["policy_id"], ["health_policies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recovery_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("workload_identity", sa.String(length=255), nullable=False),
        sa.Column("rpo_seconds", sa.Integer(), nullable=False),
        sa.Column("rto_seconds", sa.Integer(), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "rpo_seconds > 0 AND rto_seconds > 0 AND retention_days > 0",
            name="ck_recovery_policy_intervals",
        ),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_node_id", "workload_identity", name="uq_recovery_policy_workload"
        ),
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", name="uq_user_role"),
    )
    op.create_table(
        "volumes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("unique_identity", sa.String(length=255), nullable=False),
        sa.Column("filesystem", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("total_bytes", sa.BigInteger(), nullable=True),
        sa.Column("free_bytes", sa.BigInteger(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "total_bytes >= 0 AND free_bytes >= 0 AND free_bytes <= total_bytes",
            name="ck_volume_capacity",
        ),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_node_id", "unique_identity", name="uq_volume_identity"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("collector_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_identity", sa.String(length=255), nullable=True),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["collector_id"], ["collectors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "backup_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("backup_job_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_identity", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consistency", sa.String(length=32), nullable=False),
        sa.Column("storage_reference", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["backup_job_id"], ["backup_jobs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "backup_job_id", "snapshot_identity", name="uq_backup_snapshot_identity"
        ),
    )
    op.create_table(
        "collector_heartbeats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("collector_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("cursor", sa.String(length=255), nullable=True),
        sa.Column("lag_seconds", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.CheckConstraint("lag_seconds >= 0", name="ck_heartbeat_lag"),
        sa.ForeignKeyConstraint(["collector_id"], ["collectors.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_heartbeats_collector_time",
        "collector_heartbeats",
        ["collector_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "discovery_schema_families",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("schema_description", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("file_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["discovery_jobs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "duplicate_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "state IN ('CANDIDATE','HASH_PENDING','CONFIRMED','DIFFERENT_CONTENT','EXCLUDED')",
            name="ck_duplicate_state",
        ),
        sa.CheckConstraint("size_bytes >= 0 AND candidate_count >= 2", name="ck_duplicate_counts"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["hygiene_snapshots.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "filesystem_objects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("volume_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.String(length=255), nullable=False),
        sa.Column("parent_file_id", sa.String(length=255), nullable=True),
        sa.Column("object_type", sa.String(length=16), nullable=False),
        sa.Column("current_name", sa.Text(), nullable=False),
        sa.Column("current_relative_path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("object_type IN ('FILE','DIRECTORY')", name="ck_object_type"),
        sa.CheckConstraint("size_bytes >= 0", name="ck_object_size"),
        sa.ForeignKeyConstraint(["volume_id"], ["volumes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("volume_id", "file_id", name="uq_filesystem_object_identity"),
    )
    op.create_index(
        "ix_objects_volume_parent",
        "filesystem_objects",
        ["volume_id", "parent_file_id"],
        unique=False,
    )
    op.create_table(
        "group_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("member_principal_id", sa.Uuid(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["ad_groups.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["member_principal_id"], ["principals.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "member_principal_id", name="uq_group_membership"),
    )
    op.create_table(
        "health_findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("signal_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("cause_class", sa.String(length=64), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["policy_id"], ["health_policies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["signal_id"], ["health_signals.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingest_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("collector_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.String(length=255), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("last_event_at >= first_event_at", name="ck_batch_time_range"),
        sa.CheckConstraint(
            "record_count >= 0 AND schema_version = 1", name="ck_batch_schema_count"
        ),
        sa.ForeignKeyConstraint(["collector_id"], ["collectors.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_collector_batch_id", "ingest_batches", ["collector_id", "batch_id"], unique=True
    )
    op.create_table(
        "large_file_samples",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("last_write_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("size_bytes >= 0", name="ck_large_file_size"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["hygiene_snapshots.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "long_path_samples",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("path_length", sa.Integer(), nullable=False),
        sa.Column("bucket", sa.String(length=16), nullable=False),
        sa.CheckConstraint("path_length >= 0", name="ck_long_path_length"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["hygiene_snapshots.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scope_stats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("file_count", sa.BigInteger(), nullable=False),
        sa.Column("directory_count", sa.BigInteger(), nullable=False),
        sa.Column("total_bytes", sa.BigInteger(), nullable=False),
        sa.Column("zero_byte_count", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "file_count >= 0 AND directory_count >= 0 "
            "AND total_bytes >= 0 AND zero_byte_count >= 0",
            name="ck_scope_stats_counts",
        ),
        sa.ForeignKeyConstraint(["snapshot_id"], ["hygiene_snapshots.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shares",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("volume_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("protocol", sa.String(length=16), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["volume_id"], ["volumes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_node_id", "name", name="uq_share_name"),
    )
    op.create_table(
        "temp_artifact_stats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("classification", sa.String(length=16), nullable=False),
        sa.Column("file_count", sa.BigInteger(), nullable=False),
        sa.Column("total_bytes", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "classification IN ('ACTIVE','RECENT','STALE')", name="ck_temp_classification"
        ),
        sa.CheckConstraint("file_count >= 0 AND total_bytes >= 0", name="ck_temp_counts"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["hygiene_snapshots.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "volume_aliases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("volume_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["volume_id"], ["volumes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_active_volume_alias",
        "volume_aliases",
        ["volume_id", "alias"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.create_table(
        "vss_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("volume_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_identity", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["volume_id"], ["volumes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("volume_id", "snapshot_identity", name="uq_vss_identity"),
    )
    op.create_table(
        "acl_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=True),
        sa.Column("scope_identity", sa.Text(), nullable=False),
        sa.Column("dacl_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("owner_principal_id", sa.Uuid(), nullable=True),
        sa.Column("inheritance_enabled", sa.Boolean(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["object_id"], ["filesystem_objects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_principal_id"], ["principals.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "backup_verifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["snapshot_id"], ["backup_snapshots.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "change_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=True),
        sa.Column("volume_identity", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("old_relative_path", sa.Text(), nullable=True),
        sa.Column("new_relative_path", sa.Text(), nullable=True),
        sa.Column("file_id", sa.String(length=255), nullable=True),
        sa.Column("parent_file_id", sa.String(length=255), nullable=True),
        sa.Column("reason_mask", sa.String(length=64), nullable=True),
        sa.Column("source_event_id", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "event_type IN ('CREATE','WRITE','RENAME','DELETE',"
            "'METADATA_CHANGE','SECURITY_CHANGE')",
            name="ck_change_event_type",
        ),
        sa.ForeignKeyConstraint(["object_id"], ["filesystem_objects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_node_id"], ["source_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_changes_source_time", "change_events", ["source_node_id", "occurred_at"], unique=False
    )
    op.create_table(
        "discovery_series",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("schema_family_id", sa.Uuid(), nullable=True),
        sa.Column("name_pattern", sa.Text(), nullable=False),
        sa.Column("cadence", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_series_confidence"),
        sa.ForeignKeyConstraint(["job_id"], ["discovery_jobs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["schema_family_id"], ["discovery_schema_families.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incident_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["finding_id"], ["health_findings.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "object_path_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("valid_from_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["object_id"], ["filesystem_objects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_object_path_history",
        "object_path_history",
        ["object_id", "valid_from_at"],
        unique=False,
    )
    op.create_table(
        "restore_tests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("tested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("measured_rto_seconds", sa.Integer(), nullable=True),
        sa.Column("evidence_reference", sa.Text(), nullable=True),
        sa.CheckConstraint("measured_rto_seconds >= 0", name="ck_restore_duration"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["backup_snapshots.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "acl_aces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("principal_id", sa.Uuid(), nullable=True),
        sa.Column("unresolved_sid", sa.String(length=255), nullable=True),
        sa.Column("ace_type", sa.String(length=16), nullable=False),
        sa.Column("access_mask", sa.BigInteger(), nullable=False),
        sa.Column("inherited", sa.Boolean(), nullable=False),
        sa.Column("inheritance_flags", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["principal_id"], ["principals.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["acl_snapshots.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "acl_findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("finding_type", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["snapshot_id"], ["acl_snapshots.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["template_id"], ["acl_templates.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "digitization_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("series_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_state", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_digitization_confidence"),
        sa.ForeignKeyConstraint(["series_id"], ["discovery_series.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_attributions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("change_event_id", sa.Uuid(), nullable=False),
        sa.Column("principal_id", sa.Uuid(), nullable=True),
        sa.Column("client_identity", sa.String(length=255), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_attribution_confidence"),
        sa.ForeignKeyConstraint(["change_event_id"], ["change_events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["principal_id"], ["principals.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_evidence_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("change_event_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_type", sa.String(length=32), nullable=False),
        sa.Column("evidence_reference", sa.String(length=255), nullable=True),
        sa.Column("source_event_id", sa.String(length=255), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["change_event_id"], ["change_events.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_evidence_links")
    op.drop_table("event_attributions")
    op.drop_table("digitization_candidates")
    op.drop_table("acl_findings")
    op.drop_table("acl_aces")
    op.drop_table("restore_tests")
    op.drop_index("ix_object_path_history", table_name="object_path_history")
    op.drop_table("object_path_history")
    op.drop_table("incident_events")
    op.drop_table("discovery_series")
    op.drop_index("ix_changes_source_time", table_name="change_events")
    op.drop_table("change_events")
    op.drop_table("backup_verifications")
    op.drop_table("acl_snapshots")
    op.drop_table("vss_snapshots")
    op.drop_index(
        "uq_active_volume_alias",
        table_name="volume_aliases",
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.drop_table("volume_aliases")
    op.drop_table("temp_artifact_stats")
    op.drop_table("shares")
    op.drop_table("scope_stats")
    op.drop_table("long_path_samples")
    op.drop_table("large_file_samples")
    op.drop_index("uq_collector_batch_id", table_name="ingest_batches")
    op.drop_table("ingest_batches")
    op.drop_table("health_findings")
    op.drop_table("group_memberships")
    op.drop_index("ix_objects_volume_parent", table_name="filesystem_objects")
    op.drop_table("filesystem_objects")
    op.drop_table("duplicate_candidates")
    op.drop_table("discovery_schema_families")
    op.drop_index("ix_heartbeats_collector_time", table_name="collector_heartbeats")
    op.drop_table("collector_heartbeats")
    op.drop_table("backup_snapshots")
    op.drop_table("audit_log")
    op.drop_table("volumes")
    op.drop_table("user_roles")
    op.drop_table("recovery_policies")
    op.drop_table("policy_exceptions")
    op.drop_index("ix_metric_samples_1m_source_metric_time", table_name="metric_samples_1m")
    op.drop_table("metric_samples_1m")
    op.drop_index("ix_metric_samples_1h_source_metric_time", table_name="metric_samples_1h")
    op.drop_table("metric_samples_1h")
    op.drop_index("ix_metric_samples_1d_source_metric_time", table_name="metric_samples_1d")
    op.drop_table("metric_samples_1d")
    op.drop_table("incidents")
    op.drop_table("hygiene_snapshots")
    op.drop_index("ix_signals_source_domain_time", table_name="health_signals")
    op.drop_table("health_signals")
    op.drop_table("discovery_jobs")
    op.drop_table("diagnostic_bundles")
    op.drop_table("collectors")
    op.drop_table("backup_jobs")
    op.drop_table("ad_groups")
    op.drop_table("users")
    op.drop_table("source_nodes")
    op.drop_table("roles")
    op.drop_table("principals")
    op.drop_index("ix_jobs_status_due", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("health_policies")
    op.drop_table("acl_templates")
    # ### end Alembic commands ###
