from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    Index,
    Integer,
    String,
    Table,
    Text,
    UniqueConstraint,
    text,
)

from .base import identity, metadata, reference, timestamp

source_nodes = Table(
    "source_nodes",
    metadata,
    identity(),
    Column("source_type", String(16), nullable=False),
    Column("hostname", String(255), nullable=False),
    Column("fqdn", String(255)),
    Column("instance_id", String(255), nullable=False),
    Column("expected_cadence_seconds", Integer, nullable=False, server_default="60"),
    timestamp("created_at", default_now=True),
    timestamp("last_success_at", nullable=True),
    UniqueConstraint("source_type", "instance_id", name="uq_source_identity"),
    CheckConstraint("source_type IN ('FILESERVER','PVE','PBS')", name="ck_source_type"),
    CheckConstraint("expected_cadence_seconds > 0", name="ck_source_cadence"),
)
collectors = Table(
    "collectors",
    metadata,
    identity(),
    reference("source_node_id", "source_nodes.id"),
    Column("collector_type", String(32), nullable=False),
    Column("version", String(64)),
    Column("token_hash", String(64), nullable=False, unique=True),
    Column("enabled", Boolean, nullable=False, server_default="true"),
    timestamp("created_at", default_now=True),
    timestamp("last_seen_at", nullable=True),
)
collector_heartbeats = Table(
    "collector_heartbeats",
    metadata,
    identity(),
    reference("collector_id", "collectors.id"),
    timestamp("occurred_at"),
    timestamp("received_at", default_now=True),
    Column("version", String(64), nullable=False),
    Column("cursor", String(255)),
    Column("lag_seconds", Integer),
    Column("error_code", String(64)),
    CheckConstraint("lag_seconds >= 0", name="ck_heartbeat_lag"),
    Index("ix_heartbeats_collector_time", "collector_id", "occurred_at"),
)
volumes = Table(
    "volumes",
    metadata,
    identity(),
    reference("source_node_id", "source_nodes.id"),
    Column("unique_identity", String(255), nullable=False),
    Column("filesystem", String(32), nullable=False),
    Column("label", String(255)),
    Column("total_bytes", BigInteger),
    Column("free_bytes", BigInteger),
    timestamp("first_seen_at", default_now=True),
    timestamp("last_seen_at", default_now=True),
    UniqueConstraint("source_node_id", "unique_identity", name="uq_volume_identity"),
    CheckConstraint(
        "total_bytes >= 0 AND free_bytes >= 0 AND free_bytes <= total_bytes",
        name="ck_volume_capacity",
    ),
)
volume_aliases = Table(
    "volume_aliases",
    metadata,
    identity(),
    reference("volume_id", "volumes.id"),
    Column("alias", Text, nullable=False),
    timestamp("first_seen_at"),
    timestamp("last_seen_at"),
    timestamp("ended_at", nullable=True),
    Index(
        "uq_active_volume_alias",
        "volume_id",
        "alias",
        unique=True,
        postgresql_where=text("ended_at IS NULL"),
    ),
)
shares = Table(
    "shares",
    metadata,
    identity(),
    reference("source_node_id", "source_nodes.id"),
    reference("volume_id", "volumes.id", nullable=True),
    Column("name", String(255), nullable=False),
    Column("relative_path", Text, nullable=False),
    Column("protocol", String(16), nullable=False),
    timestamp("last_seen_at"),
    UniqueConstraint("source_node_id", "name", name="uq_share_name"),
)
filesystem_objects = Table(
    "filesystem_objects",
    metadata,
    identity(),
    reference("volume_id", "volumes.id"),
    Column("file_id", String(255), nullable=False),
    Column("parent_file_id", String(255)),
    Column("object_type", String(16), nullable=False),
    Column("current_name", Text, nullable=False),
    Column("current_relative_path", Text, nullable=False),
    Column("size_bytes", BigInteger),
    timestamp("first_seen_at"),
    timestamp("last_seen_at"),
    timestamp("deleted_at", nullable=True),
    UniqueConstraint("volume_id", "file_id", name="uq_filesystem_object_identity"),
    CheckConstraint("object_type IN ('FILE','DIRECTORY')", name="ck_object_type"),
    CheckConstraint("size_bytes >= 0", name="ck_object_size"),
    Index("ix_objects_volume_parent", "volume_id", "parent_file_id"),
)
object_path_history = Table(
    "object_path_history",
    metadata,
    identity(),
    reference("object_id", "filesystem_objects.id"),
    Column("relative_path", Text, nullable=False),
    timestamp("valid_from_at"),
    timestamp("valid_until_at", nullable=True),
    Index("ix_object_path_history", "object_id", "valid_from_at"),
)
